import { randomUUID } from 'node:crypto';
import { requireThat, text } from '../../domain/src/index.ts';
import type { Encounter, Observation, Operation, OperationApplication, StructuralConstraint } from '../../domain/src/index.ts';
import type { PostgresQueryable } from './postgres-driver.ts';
import { dbJson, stringList } from './postgres-driver.ts';
import { PostgresContext } from './postgres-context.ts';

export async function recordObservationTx(ctx:PostgresContext,db:PostgresQueryable,input:{explorationId:string;positionId?:string;kind:Observation['kind'];detail:string;source:string;observedAt?:string}):Promise<Observation>{
  requireThat(await ctx.exists(db,'explorations',input.explorationId,input.explorationId),'NOT_FOUND','Exploration not found.');if(input.positionId)requireThat(await ctx.exists(db,'positions',input.positionId,input.explorationId),'NOT_FOUND','Observation arrival is not in this exploration.');requireThat(['human-report','source','tool-result','measurement'].includes(input.kind),'INVALID_INPUT','Observation provenance must be external to model generation.');text(input.detail,'observation detail');text(input.source,'observation source');if(input.observedAt!==undefined)text(input.observedAt,'observedAt',200);
  const observation:Observation={id:randomUUID(),explorationId:input.explorationId,kind:input.kind,detail:input.detail,source:input.source,createdAt:ctx.stamp(),...(input.positionId?{positionId:input.positionId}:{}),...(input.observedAt?{observedAt:input.observedAt}:{})};await db.query('INSERT INTO observations(id,exploration_id,position_id,body) VALUES($1,$2,$3,$4::jsonb)',[observation.id,observation.explorationId,observation.positionId??null,dbJson(observation)]);await ctx.bumpRevision(db,observation.explorationId);await ctx.event(db,observation.explorationId,'observation.recorded',observation);return observation;
}
export async function recordConstraintTx(ctx:PostgresContext,db:PostgresQueryable,input:{explorationId:string;label:string;description:string;discoveredAtPositionId:string;provenance:StructuralConstraint['provenance'];observationIds:string[]}):Promise<StructuralConstraint>{
  requireThat(await ctx.exists(db,'explorations',input.explorationId,input.explorationId),'NOT_FOUND','Exploration not found.');requireThat(await ctx.exists(db,'positions',input.discoveredAtPositionId,input.explorationId),'NOT_FOUND','Constraint must be situated at a visited arrival.');text(input.label,'constraint label',200);text(input.description,'constraint description');requireThat(['walker-report','human-offered','observation-derived','breakdown-derived'].includes(input.provenance),'INVALID_INPUT','Invalid constraint provenance.');stringList(input.observationIds,'constraint observationIds',{max:16});for(const id of input.observationIds)requireThat(await ctx.exists(db,'observations',id,input.explorationId),'INVALID_OBSERVATION','Constraint observation is not in this exploration.');if(input.provenance==='observation-derived'||input.provenance==='breakdown-derived')requireThat(input.observationIds.length>0,'OBSERVATION_REQUIRED','Observation-derived and breakdown-derived constraints need grounded observations.');
  const constraint:StructuralConstraint={id:randomUUID(),explorationId:input.explorationId,label:input.label,description:input.description,discoveredAtPositionId:input.discoveredAtPositionId,provenance:input.provenance,observationIds:input.observationIds,epistemicStatus:'candidate',createdAt:ctx.stamp()};await db.query('INSERT INTO structural_constraints(id,exploration_id,discovered_at_position_id,body) VALUES($1,$2,$3,$4::jsonb)',[constraint.id,constraint.explorationId,constraint.discoveredAtPositionId,dbJson(constraint)]);await ctx.bumpRevision(db,constraint.explorationId);await ctx.event(db,constraint.explorationId,'constraint.recorded',constraint);return constraint;
}
export async function recordOperationTx(ctx:PostgresContext,db:PostgresQueryable,input:{explorationId:string;name:string;originDomain:string;inputStructure:string;outputStructure:string;preserves:string[];transforms:string[];procedure:string[];constraintIds:string[]}):Promise<Operation>{
  requireThat(await ctx.exists(db,'explorations',input.explorationId,input.explorationId),'NOT_FOUND','Exploration not found.');text(input.name,'operation name',200);text(input.originDomain,'operation origin domain',500);text(input.inputStructure,'operation input structure');text(input.outputStructure,'operation output structure');stringList(input.preserves,'operation preserves',{min:1,max:16});stringList(input.transforms,'operation transforms',{min:1,max:16});stringList(input.procedure,'operation procedure',{min:1,max:32});stringList(input.constraintIds,'operation constraintIds',{min:1,max:16});for(const id of input.constraintIds)requireThat(await ctx.exists(db,'structural_constraints',id,input.explorationId),'INVALID_CONSTRAINT','Operation constraint is not in this exploration.');
  const operation:Operation={id:randomUUID(),explorationId:input.explorationId,name:input.name,originDomain:input.originDomain,inputStructure:input.inputStructure,outputStructure:input.outputStructure,preserves:input.preserves,transforms:input.transforms,procedure:input.procedure,constraintIds:input.constraintIds,epistemicStatus:'candidate',createdAt:ctx.stamp()};await db.query('INSERT INTO operations(id,exploration_id,body) VALUES($1,$2,$3::jsonb)',[operation.id,operation.explorationId,dbJson(operation)]);await ctx.bumpRevision(db,operation.explorationId);await ctx.event(db,operation.explorationId,'operation.recorded',operation);return operation;
}
export async function recordApplicationTx(ctx:PostgresContext,db:PostgresQueryable,input:{explorationId:string;operationId:string;lineId:string;targetConstraintIds:string[];adaptation:string;protocol:string[];outcome:OperationApplication['outcome'];observationIds:string[];revealedConstraintIds:string[]}):Promise<OperationApplication>{
  requireThat(await ctx.exists(db,'explorations',input.explorationId,input.explorationId),'NOT_FOUND','Exploration not found.');requireThat(await ctx.exists(db,'operations',input.operationId,input.explorationId),'INVALID_OPERATION','Operation is not in this exploration.');requireThat(await ctx.exists(db,'lines',input.lineId,input.explorationId),'INVALID_LINE','Application line is not in this exploration.');stringList(input.targetConstraintIds,'application targetConstraintIds',{min:1,max:16});stringList(input.protocol,'application protocol',{min:1,max:32});stringList(input.observationIds,'application observationIds',{max:16});stringList(input.revealedConstraintIds,'application revealedConstraintIds',{max:16});text(input.adaptation,'application adaptation');requireThat(['proposed','executed','observed','broke-down'].includes(input.outcome),'INVALID_INPUT','Invalid application outcome.');for(const id of [...input.targetConstraintIds,...input.revealedConstraintIds])requireThat(await ctx.exists(db,'structural_constraints',id,input.explorationId),'INVALID_CONSTRAINT','Application constraint is not in this exploration.');for(const id of input.observationIds)requireThat(await ctx.exists(db,'observations',id,input.explorationId),'INVALID_OBSERVATION','Application observation is not in this exploration.');if(input.outcome!=='proposed')requireThat(input.observationIds.length>0,'OBSERVATION_REQUIRED','Executed, observed, or broken-down applications require external observation provenance.');if(input.outcome==='broke-down')requireThat(input.revealedConstraintIds.length>0,'CONSTRAINT_REQUIRED','A recorded breakdown must preserve at least one revealed structural constraint.');
  const application:OperationApplication={id:randomUUID(),explorationId:input.explorationId,operationId:input.operationId,lineId:input.lineId,targetConstraintIds:input.targetConstraintIds,adaptation:input.adaptation,protocol:input.protocol,outcome:input.outcome,observationIds:input.observationIds,revealedConstraintIds:input.revealedConstraintIds,createdAt:ctx.stamp()};await db.query('INSERT INTO operation_applications(id,exploration_id,operation_id,line_id,body) VALUES($1,$2,$3,$4,$5::jsonb)',[application.id,application.explorationId,application.operationId,application.lineId,dbJson(application)]);await ctx.bumpRevision(db,application.explorationId);await ctx.event(db,application.explorationId,'application.recorded',application);return application;
}
export async function recordEncounterTx(ctx:PostgresContext,db:PostgresQueryable,input:{explorationId:string;lineIds:string[];basisPositionIds:string[];kind:Encounter['kind'];summary:string;uncertainty:string[]}):Promise<Encounter>{
  requireThat(await ctx.exists(db,'explorations',input.explorationId,input.explorationId),'NOT_FOUND','Exploration not found.');stringList(input.lineIds,'encounter lineIds',{min:2,max:8});stringList(input.basisPositionIds,'encounter basisPositionIds',{min:2,max:16});stringList(input.uncertainty,'encounter uncertainty',{min:1,max:16});text(input.summary,'encounter summary');requireThat(['correspondence','tension','mismatch','partial-overlap','convergence','none'].includes(input.kind),'INVALID_INPUT','Invalid encounter kind.');for(const id of input.lineIds)requireThat(await ctx.exists(db,'lines',id,input.explorationId),'INVALID_LINE','Encounter line is not in this exploration.');for(const id of input.basisPositionIds)requireThat(await ctx.exists(db,'positions',id,input.explorationId),'INVALID_PARENT','Encounter basis arrival is not in this exploration.');const membershipResult=await db.query('SELECT line_id,position_id,role FROM line_memberships WHERE line_id = ANY($1::text[])',[input.lineIds]);const memberships=membershipResult.rows;for(const lineId of input.lineIds)requireThat(input.basisPositionIds.some(positionId=>memberships.some(m=>String(m.line_id)===lineId&&String(m.position_id)===positionId&&String(m.role)==='arrival')),'INVALID_ENCOUNTER_BASIS','Each encountered line needs at least one independently visited basis arrival beyond its origin.');requireThat(input.basisPositionIds.every(positionId=>memberships.some(m=>String(m.position_id)===positionId&&String(m.role)==='arrival')),'INVALID_ENCOUNTER_BASIS','Encounter basis must use developed arrivals rather than shared line origins.');
  const encounter:Encounter={id:randomUUID(),explorationId:input.explorationId,lineIds:input.lineIds,basisPositionIds:input.basisPositionIds,kind:input.kind,summary:input.summary,uncertainty:input.uncertainty,epistemicStatus:'candidate',createdAt:ctx.stamp()};await db.query('INSERT INTO encounters(id,exploration_id,body) VALUES($1,$2,$3::jsonb)',[encounter.id,encounter.explorationId,dbJson(encounter)]);for(const lineId of encounter.lineIds)await db.query('INSERT INTO encounter_lines(encounter_id,line_id) VALUES($1,$2)',[encounter.id,lineId]);await ctx.bumpRevision(db,encounter.explorationId);await ctx.event(db,encounter.explorationId,'encounter.recorded',encounter);return encounter;
}
