import { randomUUID } from 'node:crypto';
import { requireThat, text } from '../../domain/src/index.ts';
import type { BranchGestureRequest, Encounter, GestureRequest, GestureResolution, Line, WeaveGestureRequest, WeaveProposal } from '../../domain/src/index.ts';
import type { PostgresQueryable } from './postgres-driver.ts';
import { dbJson, decode, uniqueStrings } from './postgres-driver.ts';
import { PostgresContext } from './postgres-context.ts';

export async function paused(ctx:PostgresContext,db:PostgresQueryable,explorationId:string):Promise<void>{const live=await db.query("SELECT id FROM moves WHERE exploration_id=$1 AND status IN ('prepared','submitted') LIMIT 1",[explorationId]);requireThat(live.rows.length===0,'MOVE_IN_PROGRESS','Finish or review the current walk before changing the map from the app.');}
export async function position(ctx:PostgresContext,db:PostgresQueryable,explorationId:string,id:string):Promise<void>{requireThat(await ctx.exists(db,'positions',id,explorationId),'NOT_FOUND','Arrival is not in this exploration.');}
export async function line(_ctx:PostgresContext,db:PostgresQueryable,explorationId:string,id:string):Promise<Line>{const result=await db.query('SELECT body FROM lines WHERE id=$1 AND exploration_id=$2',[id,explorationId]);const row=result.rows[0];requireThat(row,'INVALID_LINE','Line is not in this exploration.');return decode<Line>(row.body);}
export async function unresolved(_ctx:PostgresContext,db:PostgresQueryable,requestId:string):Promise<GestureRequest>{const result=await db.query('SELECT body FROM gesture_requests WHERE id=$1',[requestId]);const row=result.rows[0];requireThat(row,'NOT_FOUND','Gesture request not found.');const resolution=await db.query('SELECT id FROM gesture_resolutions WHERE request_id=$1',[requestId]);requireThat(resolution.rows.length===0,'GESTURE_RESOLVED','This gesture request is already resolved.');return decode<GestureRequest>(row.body);}
export async function validateWeaveBasis(ctx:PostgresContext,db:PostgresQueryable,explorationId:string,lineIds:string[],basisPositionIds:string[]):Promise<void>{uniqueStrings(lineIds,'lineIds',2,8);uniqueStrings(basisPositionIds,'basisPositionIds',2,16);for(const lineId of lineIds)await line(ctx,db,explorationId,lineId);for(const positionId of basisPositionIds)await position(ctx,db,explorationId,positionId);const result=await db.query('SELECT line_id,position_id,role FROM line_memberships WHERE line_id = ANY($1::text[])',[lineIds]);const memberships=result.rows;for(const lineId of lineIds)requireThat(basisPositionIds.some(positionId=>memberships.some(m=>String(m.line_id)===lineId&&String(m.position_id)===positionId&&String(m.role)==='arrival')),'INVALID_ENCOUNTER_BASIS','Each requested line needs at least one independently visited basis arrival beyond its origin.');requireThat(basisPositionIds.every(positionId=>memberships.some(m=>String(m.position_id)===positionId&&String(m.role)==='arrival')),'INVALID_ENCOUNTER_BASIS','Weave basis must use developed arrivals rather than shared line origins.');}
export async function pendingTx(ctx:PostgresContext,db:PostgresQueryable,explorationId:string):Promise<GestureRequest[]>{const map=await ctx.cartography(db,explorationId);const resolved=new Set(map.gestureResolutions.map(r=>r.requestId));const proposed=new Set(map.weaveProposals.map(p=>p.requestId));return map.gestureRequests.filter(r=>!resolved.has(r.id)&&(r.kind==='branch'||!proposed.has(r.id)));}

export async function requestBranchTx(ctx:PostgresContext,db:PostgresQueryable,input:{explorationId:string;fromPositionId:string;label:string;direction:string}):Promise<BranchGestureRequest>{await paused(ctx,db,input.explorationId);await position(ctx,db,input.explorationId,input.fromPositionId);text(input.label,'branch label',200);text(input.direction,'branch direction');const createdAt=ctx.stamp();const branchLine:Line={id:randomUUID(),explorationId:input.explorationId,label:input.label,status:'exploratory',originPositionId:input.fromPositionId,createdAt};await db.query('INSERT INTO lines(id,exploration_id,body) VALUES($1,$2,$3::jsonb)',[branchLine.id,branchLine.explorationId,dbJson(branchLine)]);await db.query('INSERT INTO line_memberships(line_id,position_id,role,created_at) VALUES($1,$2,$3,$4)',[branchLine.id,input.fromPositionId,'origin',createdAt]);const request:BranchGestureRequest={id:randomUUID(),explorationId:input.explorationId,kind:'branch',fromPositionId:input.fromPositionId,lineId:branchLine.id,label:input.label,direction:input.direction,createdAt};await db.query('INSERT INTO gesture_requests(id,exploration_id,kind,body) VALUES($1,$2,$3,$4::jsonb)',[request.id,request.explorationId,request.kind,dbJson(request)]);await ctx.bumpRevision(db,request.explorationId);await ctx.event(db,request.explorationId,'gesture.branch.requested',{request,line:branchLine});return request;}
export async function requestWeaveTx(ctx:PostgresContext,db:PostgresQueryable,input:{explorationId:string;lineIds:string[];basisPositionIds:string[];focus:string}):Promise<WeaveGestureRequest>{await paused(ctx,db,input.explorationId);await validateWeaveBasis(ctx,db,input.explorationId,input.lineIds,input.basisPositionIds);text(input.focus,'weave focus');const request:WeaveGestureRequest={id:randomUUID(),explorationId:input.explorationId,kind:'weave',lineIds:input.lineIds,basisPositionIds:input.basisPositionIds,focus:input.focus,createdAt:ctx.stamp()};await db.query('INSERT INTO gesture_requests(id,exploration_id,kind,body) VALUES($1,$2,$3,$4::jsonb)',[request.id,request.explorationId,request.kind,dbJson(request)]);await ctx.bumpRevision(db,request.explorationId);await ctx.event(db,request.explorationId,'gesture.weave.requested',request);return request;}
export async function submitWeaveTx(ctx:PostgresContext,db:PostgresQueryable,input:{gestureRequestId:string;kind:Encounter['kind'];summary:string;uncertainty:string[]}):Promise<WeaveProposal>{const request=await unresolved(ctx,db,input.gestureRequestId);requireThat(request.kind==='weave','INVALID_GESTURE','Only weave requests accept a weave result.');await paused(ctx,db,request.explorationId);const existing=await db.query('SELECT id FROM weave_proposals WHERE request_id=$1',[request.id]);requireThat(existing.rows.length===0,'GESTURE_RESULT_EXISTS','This weave request already has a proposed result awaiting human review.');requireThat(['correspondence','tension','mismatch','partial-overlap','convergence','none'].includes(input.kind),'INVALID_INPUT','Invalid weave result kind.');text(input.summary,'weave summary');uniqueStrings(input.uncertainty,'weave uncertainty',1,16);const proposal:WeaveProposal={id:randomUUID(),explorationId:request.explorationId,requestId:request.id,version:1,status:'pending',kind:input.kind,summary:input.summary,uncertainty:input.uncertainty,createdAt:ctx.stamp()};await db.query('INSERT INTO weave_proposals(id,exploration_id,request_id,version,status,body) VALUES($1,$2,$3,$4,$5,$6::jsonb)',[proposal.id,proposal.explorationId,proposal.requestId,proposal.version,proposal.status,dbJson(proposal)]);await ctx.bumpRevision(db,proposal.explorationId);await ctx.event(db,proposal.explorationId,'gesture.weave.proposed',proposal);return proposal;}
export async function branchRequest(ctx:PostgresContext,db:PostgresQueryable,requestId:string):Promise<BranchGestureRequest>{const request=await unresolved(ctx,db,requestId);requireThat(request.kind==='branch','INVALID_GESTURE','This gesture request is not a branch request.');return request;}
export async function resolveBranch(ctx:PostgresContext,db:PostgresQueryable,requestId:string,targetId:string):Promise<void>{const request=await unresolved(ctx,db,requestId);requireThat(request.kind==='branch','INVALID_GESTURE','This gesture request is not a branch request.');await position(ctx,db,request.explorationId,targetId);const resolution:GestureResolution={id:randomUUID(),explorationId:request.explorationId,requestId:request.id,outcome:'branch-landed',targetId,createdAt:ctx.stamp()};await db.query('INSERT INTO gesture_resolutions(id,exploration_id,request_id,outcome,target_id,body) VALUES($1,$2,$3,$4,$5,$6::jsonb)',[resolution.id,resolution.explorationId,resolution.requestId,resolution.outcome,targetId,dbJson(resolution)]);await ctx.event(db,request.explorationId,'gesture.branch.landed',resolution);}
