import test from 'node:test';
import assert from 'node:assert/strict';
import { Store } from '../packages/storage/src/index.ts';
import { DomainError } from '../packages/domain/src/index.ts';
import { seed, proposal } from './fixtures.ts';

const code=(expected:string)=>(error:unknown)=>error instanceof DomainError&&error.code===expected;
function land(store:Store,explorationId:string,parentId:string,lineId:string,prefix:string,gestureRequestId?:string){const packet=store.prepare({explorationId,selectedIds:[parentId],lineId,humanDirection:`${prefix} one step.`,requestId:`${prefix}:prepare`,...(gestureRequestId?{gestureRequestId}:{})});const draft=store.submit({moveId:packet.moveId,output:proposal(parentId),requestId:`${prefix}:submit`});const ticket=store.ticket(draft.id);return store.review({draftId:draft.id,expectedVersion:ticket.version,token:ticket.token,action:'land',requestId:`${prefix}:land`});}
function developedTwoLines(store:Store){const initial=store.create(seed),root=initial.exploration.rootId,firstLine=initial.cartography.lines[0]!;const first=land(store,initial.exploration.id,root,firstLine.id,'first'),firstArrival=first.positions.at(-1)!;const forked=store.forkLine({explorationId:initial.exploration.id,fromPositionId:root,label:'Second line',requestId:'fork'}),secondLine=forked.cartography.lines.find(l=>l.label==='Second line')!;const second=land(store,initial.exploration.id,root,secondLine.id,'second'),secondArrival=second.positions.at(-1)!;return {explorationId:initial.exploration.id,root,firstLine,secondLine,firstArrival,secondArrival};}

test('human branch request creates an empty line but does not walk it',()=>{const store=new Store();try{const s=store.create(seed),root=s.exploration.rootId;const requested=store.requestBranch({explorationId:s.exploration.id,fromPositionId:root,label:'Follow the edge case',direction:'Attend to what fails to fit the current frame.',requestId:'branch-request'});assert.equal(requested.positions.length,1);assert.equal(requested.activeMove,null);const gesture=requested.cartography.gestureRequests[0]!;assert.equal(gesture.kind,'branch');if(gesture.kind!=='branch')throw new Error('expected branch');assert.equal(requested.cartography.lines.some(l=>l.id===gesture.lineId),true);assert.equal(store.pendingGestures(s.exploration.id).length,1);}finally{store.close();}});
test('requested branch resolves only after its first reviewed arrival lands',()=>{const store=new Store();try{const s=store.create(seed),root=s.exploration.rootId;const requested=store.requestBranch({explorationId:s.exploration.id,fromPositionId:root,label:'Alternative',direction:'Walk the alternative carefully.',requestId:'branch-request'});const gesture=requested.cartography.gestureRequests[0]!;if(gesture.kind!=='branch')throw new Error('expected branch');const packet=store.prepare({explorationId:s.exploration.id,selectedIds:[root],lineId:gesture.lineId,gestureRequestId:gesture.id,humanDirection:gesture.direction,requestId:'prepare'});assert.equal(store.pendingGestures(s.exploration.id).length,1);const draft=store.submit({moveId:packet.moveId,output:proposal(root),requestId:'submit'}),cap=store.ticket(draft.id);const landed=store.review({draftId:draft.id,expectedVersion:cap.version,token:cap.token,action:'land',requestId:'land'});const resolution=landed.cartography.gestureResolutions.find(r=>r.requestId===gesture.id)!;assert.equal(resolution.outcome,'branch-landed');assert.equal(store.pendingGestures(s.exploration.id).length,0);}finally{store.close();}});
test('branch request cannot be falsely fulfilled on another line',()=>{const store=new Store();try{const s=store.create(seed),root=s.exploration.rootId,original=s.cartography.lines[0]!;const requested=store.requestBranch({explorationId:s.exploration.id,fromPositionId:root,label:'Alternative',direction:'Stay on the alternative.',requestId:'branch-request'});const gesture=requested.cartography.gestureRequests[0]!;if(gesture.kind!=='branch')throw new Error('expected branch');assert.throws(()=>store.prepare({explorationId:s.exploration.id,selectedIds:[root],lineId:original.id,gestureRequestId:gesture.id,humanDirection:'Wrong line.',requestId:'wrong'}),code('INVALID_GESTURE'));}finally{store.close();}});
test('weave request preserves human focus without creating an encounter',()=>{const store=new Store();try{const d=developedTwoLines(store);const requested=store.requestWeave({explorationId:d.explorationId,lineIds:[d.firstLine.id,d.secondLine.id],basisPositionIds:[d.firstArrival.id,d.secondArrival.id],focus:'Test whether the two lines share a structural bottleneck; mismatch is acceptable.',requestId:'weave-request'});assert.equal(requested.cartography.encounters.length,0);assert.equal(requested.cartography.weaveProposals.length,0);assert.equal(store.pendingGestures(d.explorationId).length,1);}finally{store.close();}});
test('model weave result remains proposed until human review keeps it',()=>{const store=new Store();try{const d=developedTwoLines(store),requested=store.requestWeave({explorationId:d.explorationId,lineIds:[d.firstLine.id,d.secondLine.id],basisPositionIds:[d.firstArrival.id,d.secondArrival.id],focus:'Look for tension without forcing synthesis.',requestId:'weave-request'}),gesture=requested.cartography.gestureRequests.at(-1)!;const p=store.submitWeaveResult({gestureRequestId:gesture.id,kind:'tension',summary:'The lines preserve different notions of what must remain invariant.',uncertainty:['The tension may dissolve under another representation.'],requestId:'weave-result'});assert.equal(p.status,'pending');assert.equal(store.read(d.explorationId).cartography.encounters.length,0);const cap=store.weaveTicket(p.id),args={proposalId:p.id,expectedVersion:cap.version,token:cap.token,action:'keep' as const,requestId:'weave-review'};const kept=store.reviewWeaveResult(args);assert.equal(kept.cartography.encounters[0]!.kind,'tension');assert.deepEqual(store.reviewWeaveResult(args),kept);}finally{store.close();}});
test('human may keep none and may discard speculative synthesis',()=>{const store=new Store();try{const d=developedTwoLines(store);let s=store.requestWeave({explorationId:d.explorationId,lineIds:[d.firstLine.id,d.secondLine.id],basisPositionIds:[d.firstArrival.id,d.secondArrival.id],focus:'Check whether anything useful connects.',requestId:'none-request'}),req=s.cartography.gestureRequests.at(-1)!,p=store.submitWeaveResult({gestureRequestId:req.id,kind:'none',summary:'No useful structural correspondence survived comparison.',uncertainty:['A later re-walk could change the basis.'],requestId:'none-result'}),cap=store.weaveTicket(p.id);s=store.reviewWeaveResult({proposalId:p.id,expectedVersion:cap.version,token:cap.token,action:'keep',requestId:'none-review'});assert.equal(s.cartography.encounters.at(-1)!.kind,'none');s=store.requestWeave({explorationId:d.explorationId,lineIds:[d.firstLine.id,d.secondLine.id],basisPositionIds:[d.firstArrival.id,d.secondArrival.id],focus:'Try another comparison.',requestId:'discard-request'});req=s.cartography.gestureRequests.at(-1)!;p=store.submitWeaveResult({gestureRequestId:req.id,kind:'correspondence',summary:'A speculative correspondence.',uncertainty:['It may be surface resemblance only.'],requestId:'discard-result'});cap=store.weaveTicket(p.id);s=store.reviewWeaveResult({proposalId:p.id,expectedVersion:cap.version,token:cap.token,action:'discard',requestId:'discard-review'});assert.equal(s.cartography.encounters.length,1);assert.equal(s.cartography.weaveProposals.at(-1)!.status,'discarded');}finally{store.close();}});
test('weave rejects shared origins and app gestures cannot invalidate a live walk',()=>{const store=new Store();try{const s=store.create(seed),root=s.exploration.rootId,forked=store.forkLine({explorationId:s.exploration.id,fromPositionId:root,label:'Other',requestId:'fork'}),ls=forked.cartography.lines;assert.throws(()=>store.requestWeave({explorationId:s.exploration.id,lineIds:[ls[0]!.id,ls[1]!.id],basisPositionIds:[root],focus:'This should fail.',requestId:'bad-weave'}),code('INVALID_INPUT'));store.prepare({explorationId:s.exploration.id,selectedIds:[root],lineId:ls[0]!.id,humanDirection:'Live walk.',requestId:'prepare'});assert.throws(()=>store.requestBranch({explorationId:s.exploration.id,fromPositionId:root,label:'Unsafe branch',direction:'Would stale the live walk.',requestId:'unsafe'}),code('MOVE_IN_PROGRESS'));}finally{store.close();}});
