import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import type { CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import { registerAppTool, registerAppResource, RESOURCE_MIME_TYPE } from '@modelcontextprotocol/ext-apps/server';
import { DomainError, requireThat } from '../../../packages/domain/src/index.ts';
import type { Snapshot } from '../../../packages/domain/src/index.ts';
import { Store } from '../../../packages/storage/src/index.ts';
import { inputs, outputs, UI_URI, TICKET_META } from '../../../packages/protocol/src/index.ts';

export function createMcpServer(store: Store, widgetHtml: string): McpServer {
  const server = new McpServer({name:'shadow-walker',version:'0.5.0'}, {instructions:
    'Shadow Walker is a persistent toolkit for situated latent-space cartography synthesizing Semantic Walk and Flight Lines. The host model performs path-dependent reasoning; the server preserves arrivals, lines, persistent sensed waypoints, situated traversal provenance, re-walks, semantic shifts, observations, candidate constraints, executable operations, applications, encounters, uncertainty and human review. Semantic shifts are walker reports, never hidden-state measurements. Observations must come from a human, source, tool result, or measurement; never fabricate one. An operation needs explicit input/output structure, invariants, transformation and procedure: resemblance alone is not an operation. Executed or broken-down applications require grounded observations, and breakdowns preserve newly revealed constraints. Encounters compare independently developed lines and may legitimately record no useful correspondence. Resonance proposes; it does not prove. A human reviews arrival drafts in the app. Never call review_draft as the model, infer acceptance, automatically continue after review, or describe acceptance as verification. No server-side model runs.'});
  const annotations=(readOnly:boolean)=>({readOnlyHint:readOnly,destructiveHint:false,openWorldHint:false});
  const ui={ui:{resourceUri:UI_URI},'openai/outputTemplate':UI_URI,'openai/widgetAccessible':true};
  const safe=<T,>(fn:(args:T)=>CallToolResult)=>async(args:T):Promise<CallToolResult>=>{
    try{return fn(args);}catch(error){const known=error instanceof DomainError;if(!known)console.error('Shadow Walker tool failed:',error instanceof Error?error.name:'unknown');return {isError:true,content:[{type:'text',text:JSON.stringify({code:known?error.code:'INTERNAL_ERROR',message:known?error.message:'The operation failed. Reopen the exploration before continuing.'})}]};}
  };
  const result=(snapshot:Snapshot,draftId?:string):CallToolResult=>{
    const d=draftId?snapshot.drafts.find(d=>d.id===draftId):undefined;requireThat(!draftId||d,'NOT_FOUND','Draft is not in this exploration.');
    const map=snapshot.cartography;
    return {structuredContent:{snapshot,...(draftId?{focusedDraftId:draftId}:{})},content:[{type:'text',text:`${snapshot.exploration.title}: ${snapshot.positions.length} visited arrivals, ${map.lines.length} line${map.lines.length===1?'':'s'}, ${map.waypoints.filter(w=>w.status==='sensed').length} sensed route${map.waypoints.filter(w=>w.status==='sensed').length===1?'':'s'}, ${map.constraints.length} candidate constraint${map.constraints.length===1?'':'s'}, ${map.operations.length} operation${map.operations.length===1?'':'s'}, ${map.encounters.length} encounter${map.encounters.length===1?'':'s'}. ${d?`Draft ${d.status}, revision ${d.version}. `:''}Acceptance is not verification. Wait for human direction before any next move.`}],...(d&&(d.status==='pending'||d.status==='reserved')?{_meta:{[TICKET_META]:store.ticket(d.id)}}:{})};
  };

  registerAppTool(server,'create_exploration',{description:'Record an explicitly requested human intention and initial frame. Creates the root arrival and first line; it is not a generated finding.',inputSchema:inputs.create,outputSchema:outputs.snapshot,annotations:annotations(false),_meta:ui},safe<Parameters<Store['create']>[0]>(args=>result(store.create(args))));
  server.registerTool('list_explorations',{description:'List up to 100 most recently created explorations.',inputSchema:{},outputSchema:outputs.list,annotations:annotations(true)},safe(()=>({structuredContent:{explorations:store.list()},content:[{type:'text',text:'Saved explorations.'}]})));
  server.registerTool('read_exploration',{description:'Read visited arrivals, lines/transitions, Flight Lines objects and draft history. Returns no review capability.',inputSchema:inputs.read,outputSchema:outputs.snapshot,annotations:annotations(true)},safe<{explorationId:string}>(args=>result(store.read(args.explorationId))));
  registerAppTool(server,'open_exploration',{description:'Open the cartographic map and human review UI. Review credentials are delivered only in widget metadata.',inputSchema:inputs.open,outputSchema:outputs.snapshot,annotations:annotations(false),_meta:ui},safe<{explorationId:string;draftId?:string}>(args=>{const snapshot=store.read(args.explorationId);return result(snapshot,args.draftId??snapshot.drafts.find(d=>d.status==='pending')?.id);}));

  server.registerTool('fork_line',{description:'Preserve an explicit alternative line starting from a visited arrival. This records possibility without visiting new territory.',inputSchema:inputs.fork,outputSchema:outputs.snapshot,annotations:annotations(false)},safe<Parameters<Store['forkLine']>[0]>(args=>result(store.forkLine(args))));
  server.registerTool('record_waypoint',{description:'Persist a sensed but unvisited direction from a visited arrival. Use provenance to say how the route appeared; recording it does not visit or verify anything.',inputSchema:inputs.waypoint,outputSchema:outputs.snapshot,annotations:annotations(false)},safe<Parameters<Store['recordWaypoint']>[0]>(args=>result(store.recordWaypoint(args))));
  server.registerTool('dissipate_waypoint',{description:'Mark a still-sensed route as dissipated when the human explicitly decides it should no longer remain live. The route stays in history and is not treated as visited.',inputSchema:inputs.dissipateWaypoint,outputSchema:outputs.snapshot,annotations:annotations(false)},safe<Parameters<Store['dissipateWaypoint']>[0]>(args=>result(store.dissipateWaypoint(args))));
  server.registerTool('record_observation',{description:'Record externally grounded evidence introduced by a human, source, tool result, or measurement. Never use this for model inference or prediction.',inputSchema:inputs.observation,outputSchema:outputs.snapshot,annotations:annotations(false)},safe<Parameters<Store['recordObservation']>[0]>(args=>result(store.recordObservation(args))));
  server.registerTool('record_constraint',{description:'Record a candidate structural constraint situated at a visited arrival. Observation-derived and breakdown-derived constraints require observation IDs; this does not establish truth.',inputSchema:inputs.constraint,outputSchema:outputs.snapshot,annotations:annotations(false)},safe<Parameters<Store['recordConstraint']>[0]>(args=>result(store.recordConstraint(args))));
  server.registerTool('record_operation',{description:'Record a candidate deterritorialized operation only when its mechanics are explicit: input structure, output structure, invariants preserved, transformation, executable procedure, and the constraints it may act on. A metaphor or resemblance is insufficient.',inputSchema:inputs.operation,outputSchema:outputs.snapshot,annotations:annotations(false)},safe<Parameters<Store['recordOperation']>[0]>(args=>result(store.recordOperation(args))));
  server.registerTool('record_application',{description:'Record a situated application of an operation to one line. Proposed applications need a concrete protocol; executed/observed/broken-down outcomes require grounded observations. A breakdown also requires at least one preserved revealed constraint.',inputSchema:inputs.application,outputSchema:outputs.snapshot,annotations:annotations(false)},safe<Parameters<Store['recordApplication']>[0]>(args=>result(store.recordApplication(args))));
  server.registerTool('record_encounter',{description:'Record a deliberate comparison/weave between at least two independently represented lines using visited basis arrivals. Result may be correspondence, tension, mismatch, partial overlap, convergence, or none; do not force synthesis.',inputSchema:inputs.encounter,outputSchema:outputs.snapshot,annotations:annotations(false)},safe<Parameters<Store['recordEncounter']>[0]>(args=>result(store.recordEncounter(args))));

  server.registerTool('prepare_move',{description:'Prepare exactly one guided semantic walk on one explicit line. Optionally follow a persisted sensed waypoint with waypointId or explicitly re-walk a selected visited arrival with rewalkOfPositionId. traversalContext is declared provenance, not a reproducibility guarantee. If a selected arrival belongs to multiple lines, supply lineId rather than implicitly collapsing them. Do not prepare again until human direction resumes the walk.',inputSchema:inputs.prepare,outputSchema:outputs.packet,annotations:annotations(false)},safe<Parameters<Store['prepare']>[0]>(args=>({structuredContent:{packet:store.prepare(args)},content:[{type:'text',text:'Perform one path-dependent walk or explicit re-walk, report its semantic shift, submit one draft, then stop for human review.'}]})));
  registerAppTool(server,'submit_move',{description:'Save one or two proposed arrivals as an unaccepted draft. New cartographic moves require semantic-shift reports. This does not land arrivals or start a follow-up.',inputSchema:inputs.submit,outputSchema:outputs.snapshot,annotations:annotations(false),_meta:ui},safe<Parameters<Store['submit']>[0]>(args=>{const draft=store.submit(args);return result(store.read(draft.explorationId),draft.id);}));
  registerAppTool(server,'review_draft',{description:'Human review UI only. Requires a single-use capability for this exact draft revision. Keeping/Landing accepts an arrival but does not verify it.',inputSchema:inputs.review,outputSchema:outputs.snapshot,annotations:annotations(false),_meta:{...ui,ui:{resourceUri:UI_URI,visibility:['app']}}},safe<Parameters<Store['review']>[0]>(args=>result(store.review(args),args.draftId)));
  registerAppResource(server,'shadow-walker-review',UI_URI,{mimeType:RESOURCE_MIME_TYPE},async()=>({contents:[{uri:UI_URI,mimeType:RESOURCE_MIME_TYPE,text:widgetHtml,_meta:{ui:{prefersBorder:true,csp:{connectDomains:[],resourceDomains:[]}},'openai/widgetDescription':'Map conceptual territory, Flight Lines objects, and review one proposed arrival. Keeping it records acceptance, not truth.'}}]}));
  return server;
}
