import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import type { CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import { registerAppTool, registerAppResource, RESOURCE_MIME_TYPE } from '@modelcontextprotocol/ext-apps/server';
import { DomainError, requireThat } from '../../../packages/domain/src/index.ts';
import type { Snapshot } from '../../../packages/domain/src/index.ts';
import { Store } from '../../../packages/storage/src/index.ts';

type Awaitable<T> = T | Promise<T>;
type McpStoreMethod =
  | 'create' | 'list' | 'read' | 'forkLine' | 'recordWaypoint' | 'dissipateWaypoint'
  | 'requestBranch' | 'requestWeave' | 'dismissGesture' | 'pendingGestures' | 'submitWeaveResult'
  | 'reviewWeaveResult' | 'recordObservation' | 'recordConstraint' | 'recordOperation' | 'recordApplication'
  | 'recordEncounter' | 'prepare' | 'submit' | 'review' | 'ticket' | 'weaveTicket';
type McpStore = {
  [K in McpStoreMethod]: Store[K] extends (...args: infer A) => infer R ? (...args: A) => Awaitable<R> : never;
};
import { inputs, outputs, UI_URI, TICKET_META, WEAVE_TICKET_META } from '../../../packages/protocol/src/index.ts';

export function createMcpServer(store: McpStore, widgetHtml: string): McpServer {
  const server = new McpServer({name:'shadow-walker',version:'0.6.0'}, {instructions:
    'Shadow Walker is a persistent toolkit for situated latent-space cartography synthesizing Semantic Walk and Flight Lines. The host model performs path-dependent reasoning; the server preserves arrivals, lines, persistent sensed waypoints, situated traversals/re-walks, semantic shifts, grounded observations, candidate constraints, executable operations/applications, encounters, and human-directed coordination gestures. Human branch/weave requests are durable intentions, not autonomous permission: when the human asks to resume, inspect list_pending_gestures. A branch request is fulfilled by one explicit prepare_move on its requested line with gestureRequestId, then submit one Arrival draft and stop for human review. A weave request must be reasoned over using its exact developed lines, basis arrivals, and focus; submit_weave_result records only a proposal, then stop for human weave review. Never call review_draft or review_weave_result as the model, extract their capabilities, or infer acceptance. Semantic shifts are walker reports, never hidden-state measurements. Traversal context is declared provenance, never a reproducibility guarantee. A weave may legitimately yield mismatch or none. Resonance proposes; it does not prove. No server-side model runs and no review action automatically continues the exploration.'});
  const annotations=(readOnly:boolean)=>({readOnlyHint:readOnly,destructiveHint:false,openWorldHint:false});
  const widgetDomain='https://shadow-walker.vercel.app';
  const ui={ui:{resourceUri:UI_URI},'openai/outputTemplate':UI_URI,'openai/widgetAccessible':true};
  const safe=<T,>(fn:(args:T)=>Awaitable<CallToolResult>)=>async(args:T):Promise<CallToolResult>=>{
    try{return await fn(args);}catch(error){const known=error instanceof DomainError;if(!known)console.error('Shadow Walker tool failed:',error instanceof Error?error.name:'unknown');return {isError:true,content:[{type:'text',text:JSON.stringify({code:known?error.code:'INTERNAL_ERROR',message:known?error.message:'The operation failed. Reopen the exploration before continuing.'})}]};}
  };
  const result=async(snapshotValue:Awaitable<Snapshot>,draftId?:string,weaveProposalId?:string):Promise<CallToolResult>=>{
    const snapshot=await snapshotValue;
    const d=draftId?snapshot.drafts.find(d=>d.id===draftId):undefined;requireThat(!draftId||d,'NOT_FOUND','Draft is not in this exploration.');
    const wp=weaveProposalId?snapshot.cartography.weaveProposals.find(p=>p.id===weaveProposalId):undefined;requireThat(!weaveProposalId||wp,'NOT_FOUND','Weave proposal is not in this exploration.');
    const map=snapshot.cartography;const resolved=new Set(map.gestureResolutions.map(r=>r.requestId));const proposed=new Set(map.weaveProposals.filter(p=>p.status==='pending').map(p=>p.requestId));const pending=map.gestureRequests.filter(r=>!resolved.has(r.id)&&(r.kind==='branch'||!proposed.has(r.id))).length;
    const meta:Record<string,unknown>={};if(d&&(d.status==='pending'||d.status==='reserved'))meta[TICKET_META]=await store.ticket(d.id);if(wp&&wp.status==='pending')meta[WEAVE_TICKET_META]=await store.weaveTicket(wp.id);
    return {structuredContent:{snapshot,...(draftId?{focusedDraftId:draftId}:{}),...(weaveProposalId?{focusedWeaveProposalId:weaveProposalId}:{})},content:[{type:'text',text:`${snapshot.exploration.title}: ${snapshot.positions.length} visited arrivals, ${map.lines.length} line${map.lines.length===1?'':'s'}, ${map.waypoints.filter(w=>w.status==='sensed').length} sensed route${map.waypoints.filter(w=>w.status==='sensed').length===1?'':'s'}, ${map.constraints.length} candidate constraint${map.constraints.length===1?'':'s'}, ${map.operations.length} operation${map.operations.length===1?'':'s'}, ${map.encounters.length} encounter${map.encounters.length===1?'':'s'}, ${pending} pending human gesture${pending===1?'':'s'}. ${d?`Arrival draft ${d.status}, revision ${d.version}. `:''}${wp?`Weave proposal ${wp.status}, revision ${wp.version}. `:''}Acceptance is not verification. Wait for human direction before any next move.`}],...(Object.keys(meta).length?{_meta:meta}:{})};
  };

  registerAppTool(server,'create_exploration',{description:'Record an explicitly requested human intention and initial frame. Creates the root arrival and first line; it is not a generated finding.',inputSchema:inputs.create,outputSchema:outputs.snapshot,annotations:annotations(false),_meta:ui},safe<Parameters<Store['create']>[0]>(args=>result(store.create(args))));
  server.registerTool('list_explorations',{description:'List up to 100 most recently created explorations.',inputSchema:{},outputSchema:outputs.list,annotations:annotations(true)},safe(async()=>({structuredContent:{explorations:await store.list()},content:[{type:'text',text:'Saved explorations.'}]})));
  server.registerTool('read_exploration',{description:'Read visited arrivals, lines/transitions, Flight Lines objects and draft history. Returns no review capability.',inputSchema:inputs.read,outputSchema:outputs.snapshot,annotations:annotations(true)},safe<{explorationId:string}>(args=>result(store.read(args.explorationId))));
  registerAppTool(server,'open_exploration',{description:'Open the cartographic map and human review UI. Arrival and weave review credentials are delivered only in widget metadata.',inputSchema:inputs.open,outputSchema:outputs.snapshot,annotations:annotations(false),_meta:ui},safe<{explorationId:string;draftId?:string}>(async args=>{const snapshot=await store.read(args.explorationId);return result(snapshot,args.draftId??snapshot.drafts.find(d=>d.status==='pending')?.id,snapshot.cartography.weaveProposals.find(p=>p.status==='pending')?.id);}));

  server.registerTool('fork_line',{description:'Preserve an explicit alternative line starting from a visited arrival. This records possibility without visiting new territory.',inputSchema:inputs.fork,outputSchema:outputs.snapshot,annotations:annotations(false)},safe<Parameters<Store['forkLine']>[0]>(args=>result(store.forkLine(args))));
  server.registerTool('record_waypoint',{description:'Persist a sensed but unvisited direction from a visited arrival. Use provenance to say how the route appeared; recording it does not visit or verify anything.',inputSchema:inputs.waypoint,outputSchema:outputs.snapshot,annotations:annotations(false)},safe<Parameters<Store['recordWaypoint']>[0]>(args=>result(store.recordWaypoint(args))));
  server.registerTool('dissipate_waypoint',{description:'Mark a still-sensed route as dissipated when the human explicitly decides it should no longer remain live. The route stays in history and is not treated as visited.',inputSchema:inputs.dissipateWaypoint,outputSchema:outputs.snapshot,annotations:annotations(false)},safe<Parameters<Store['dissipateWaypoint']>[0]>(args=>result(store.dissipateWaypoint(args))));
  registerAppTool(server,'request_branch',{description:'Human map action only. Preserve an explicit branch intention and empty line without visiting new territory or running the model.',inputSchema:inputs.requestBranch,outputSchema:outputs.snapshot,annotations:annotations(false),_meta:{...ui,ui:{resourceUri:UI_URI,visibility:['app']}}},safe<Parameters<Store['requestBranch']>[0]>(args=>result(store.requestBranch(args))));
  registerAppTool(server,'request_weave',{description:'Human map action only. Ask the conversation to bring independently developed lines into deliberate encounter. This stores focus and basis; it does not synthesize anything.',inputSchema:inputs.requestWeave,outputSchema:outputs.snapshot,annotations:annotations(false),_meta:{...ui,ui:{resourceUri:UI_URI,visibility:['app']}}},safe<Parameters<Store['requestWeave']>[0]>(args=>result(store.requestWeave(args))));
  registerAppTool(server,'dismiss_gesture_request',{description:'Human map action only. Dismiss a pending branch/weave request. A weave with a pending result must be reviewed instead.',inputSchema:inputs.dismissGesture,outputSchema:outputs.snapshot,annotations:annotations(false),_meta:{...ui,ui:{resourceUri:UI_URI,visibility:['app']}}},safe<Parameters<Store['dismissGesture']>[0]>(args=>result(store.dismissGesture(args))));
  server.registerTool('list_pending_gestures',{description:'List unresolved human branch/weave intentions that need conversational reasoning. Do not treat their existence as permission for more than the gesture the human has asked to resume.',inputSchema:inputs.pendingGestures,outputSchema:outputs.pendingGestures,annotations:annotations(true)},safe<{explorationId:string}>(async args=>({structuredContent:{requests:await store.pendingGestures(args.explorationId)},content:[{type:'text',text:'Pending human cartographic gestures. Fulfill at most the gesture the human has asked to resume, then stop at its review boundary.'}]})));
  registerAppTool(server,'submit_weave_result',{description:'Submit the conversational result of one human-requested weave as a pending proposal. This does not create an Encounter; human review is still required. Mismatch and none are valid.',inputSchema:inputs.submitWeave,outputSchema:outputs.snapshot,annotations:annotations(false),_meta:ui},safe<Parameters<Store['submitWeaveResult']>[0]>(async args=>{const proposal=await store.submitWeaveResult(args);const snapshot=await store.read(proposal.explorationId);return result(snapshot,undefined,proposal.id);}));
  registerAppTool(server,'review_weave_result',{description:'Human review UI only. Requires a single-use capability for this exact weave proposal revision. Keep creates a candidate Encounter; discard creates none.',inputSchema:inputs.reviewWeave,outputSchema:outputs.snapshot,annotations:annotations(false),_meta:{...ui,ui:{resourceUri:UI_URI,visibility:['app']}}},safe<Parameters<Store['reviewWeaveResult']>[0]>(args=>result(store.reviewWeaveResult(args),undefined,args.proposalId)));
  server.registerTool('record_observation',{description:'Record externally grounded evidence introduced by a human, source, tool result, or measurement. Never use this for model inference or prediction.',inputSchema:inputs.observation,outputSchema:outputs.snapshot,annotations:annotations(false)},safe<Parameters<Store['recordObservation']>[0]>(args=>result(store.recordObservation(args))));
  server.registerTool('record_constraint',{description:'Record a candidate structural constraint situated at a visited arrival. Observation-derived and breakdown-derived constraints require observation IDs; this does not establish truth.',inputSchema:inputs.constraint,outputSchema:outputs.snapshot,annotations:annotations(false)},safe<Parameters<Store['recordConstraint']>[0]>(args=>result(store.recordConstraint(args))));
  server.registerTool('record_operation',{description:'Record a candidate deterritorialized operation only when its mechanics are explicit: input structure, output structure, invariants preserved, transformation, executable procedure, and the constraints it may act on. A metaphor or resemblance is insufficient.',inputSchema:inputs.operation,outputSchema:outputs.snapshot,annotations:annotations(false)},safe<Parameters<Store['recordOperation']>[0]>(args=>result(store.recordOperation(args))));
  server.registerTool('record_application',{description:'Record a situated application of an operation to one line. Proposed applications need a concrete protocol; executed/observed/broken-down outcomes require grounded observations. A breakdown also requires at least one preserved revealed constraint.',inputSchema:inputs.application,outputSchema:outputs.snapshot,annotations:annotations(false)},safe<Parameters<Store['recordApplication']>[0]>(args=>result(store.recordApplication(args))));
  server.registerTool('record_encounter',{description:'Record a deliberate comparison/weave between at least two independently represented lines using visited basis arrivals. Result may be correspondence, tension, mismatch, partial overlap, convergence, or none; do not force synthesis.',inputSchema:inputs.encounter,outputSchema:outputs.snapshot,annotations:annotations(false)},safe<Parameters<Store['recordEncounter']>[0]>(args=>result(store.recordEncounter(args))));

  server.registerTool('prepare_move',{description:'Prepare exactly one guided semantic walk on one explicit line. Optionally follow a persisted waypoint, explicitly re-walk a selected Arrival, or fulfill one pending human branch request using its exact gestureRequestId and requested line/origin. traversalContext is declared provenance, not a reproducibility guarantee. Stop at the human review boundary.',inputSchema:inputs.prepare,outputSchema:outputs.packet,annotations:annotations(false)},safe<Parameters<Store['prepare']>[0]>(async args=>({structuredContent:{packet:await store.prepare(args)},content:[{type:'text',text:'Perform one path-dependent walk or explicit re-walk, report its semantic shift, submit one draft, then stop for human review.'}]})));
  registerAppTool(server,'submit_move',{description:'Save one or two proposed arrivals as an unaccepted draft. New cartographic moves require semantic-shift reports. This does not land arrivals or start a follow-up.',inputSchema:inputs.submit,outputSchema:outputs.snapshot,annotations:annotations(false),_meta:ui},safe<Parameters<Store['submit']>[0]>(async args=>{const draft=await store.submit(args);return result(store.read(draft.explorationId),draft.id);}));
  registerAppTool(server,'review_draft',{description:'Human review UI only. Requires a single-use capability for this exact draft revision. Keeping/Landing accepts an arrival but does not verify it.',inputSchema:inputs.review,outputSchema:outputs.snapshot,annotations:annotations(false),_meta:{...ui,ui:{resourceUri:UI_URI,visibility:['app']}}},safe<Parameters<Store['review']>[0]>(args=>result(store.review(args),args.draftId)));
  const widgetResourceMeta={ui:{domain:widgetDomain,prefersBorder:true,csp:{connectDomains:[],resourceDomains:[]}},'openai/widgetDomain':widgetDomain,'openai/widgetPrefersBorder':true,'openai/widgetCSP':{connect_domains:[],resource_domains:[]},'openai/widgetDescription':'Map conceptual territory and Flight Lines objects; request branches/weaves and review proposed arrivals or weave results. Human review records acceptance, not truth.'};
  registerAppResource(server,'shadow-walker-review',UI_URI,{mimeType:RESOURCE_MIME_TYPE,_meta:widgetResourceMeta},async()=>({contents:[{uri:UI_URI,mimeType:RESOURCE_MIME_TYPE,text:widgetHtml,_meta:widgetResourceMeta}]}));
  return server;
}
