import { useMemo, useRef, useState } from 'react';
import type {
  BranchGestureRequest, Encounter, Observation, Operation, OperationApplication, Position, Proposal, SemanticShift, Snapshot,
  StructuralConstraint, Traversal, Waypoint, WeaveGestureRequest, WeaveProposal,
} from '../../../packages/domain/src/index.ts';
import './map-readability.css';

const short=(value:string,max=72)=>value.length<=max?value:`${value.slice(0,max-1).trimEnd()}…`;

export type VisualNode={
  id:string;type:'arrival'|'draft'|'waypoint'|'branch';label:string;parentIds:string[];position?:Position;proposal?:Proposal;waypoint?:Waypoint;branch?:BranchGestureRequest;
  draftId?:string;draftStatus?:'pending'|'reserved'|'landed'|'discarded';question?:string;shift?:SemanticShift;index:number;legacyWaypoint?:boolean;
};
export type MapLayers={evidence:boolean;structure:boolean;operations:boolean;encounters:boolean};
type Point={x:number;y:number;depth:number};
type VisualFeature=
  | {id:string;kind:'observation';label:string;anchorIds:string[];observation:Observation}
  | {id:string;kind:'constraint';label:string;anchorIds:string[];constraint:StructuralConstraint}
  | {id:string;kind:'operation';label:string;anchorIds:string[];operation:Operation}
  | {id:string;kind:'application';label:string;anchorIds:string[];application:OperationApplication}
  | {id:string;kind:'encounter';label:string;anchorIds:string[];encounter:Encounter}
  | {id:string;kind:'weave-request';label:string;anchorIds:string[];request:WeaveGestureRequest;proposal?:WeaveProposal};

function unresolvedGestureIds(snapshot:Snapshot):Set<string>{return new Set(snapshot.cartography.gestureResolutions.map(r=>r.requestId));}

export function mapNodes(snapshot:Snapshot):VisualNode[]{
  const nodes:VisualNode[]=snapshot.positions.map((position,index)=>({id:position.id,type:'arrival',label:position.kind==='intention'?snapshot.exploration.title:short(position.meaning),parentIds:position.parentIds,position,shift:position.semanticShift,index}));
  let index=nodes.length;
  for(const draft of snapshot.drafts.filter(d=>d.status==='pending'||d.status==='reserved')){
    const local=new Map(draft.output.positions.map(p=>[`draft:${p.localId}`,`proposal:${draft.id}:${p.localId}`]));
    for(const p of draft.output.positions)nodes.push({id:`proposal:${draft.id}:${p.localId}`,type:'draft',label:short(p.meaning),parentIds:p.parentIds.map(id=>local.get(id)??id),proposal:p,shift:p.semanticShift,draftId:draft.id,draftStatus:draft.status,index:index++});
  }
  const persistedOrigins=new Set(snapshot.cartography.waypoints.map(w=>w.fromPositionId));
  for(const waypoint of snapshot.cartography.waypoints.filter(w=>w.status!=='visited'))nodes.push({id:`waypoint:${waypoint.id}`,type:'waypoint',label:short(waypoint.question),parentIds:[waypoint.fromPositionId],question:waypoint.question,waypoint,index:index++});
  const resolved=unresolvedGestureIds(snapshot);
  for(const request of snapshot.cartography.gestureRequests)if(request.kind==='branch'&&!resolved.has(request.id))nodes.push({id:`branch:${request.id}`,type:'branch',label:short(request.label),parentIds:[request.fromPositionId],branch:request,index:index++});
  for(const position of snapshot.positions){
    const hasChild=nodes.some(n=>n.parentIds.includes(position.id)&&n.type!=='waypoint'&&n.type!=='branch');
    if(position.kind!=='intention'&&!persistedOrigins.has(position.id)&&!hasChild&&position.nextQuestion)nodes.push({id:`legacy-waypoint:${position.id}`,type:'waypoint',label:short(position.nextQuestion),parentIds:[position.id],question:position.nextQuestion,index:index++,legacyWaypoint:true});
  }
  return nodes;
}
function layout(nodes:VisualNode[]):{points:Map<string,Point>;width:number;height:number}{
  const byId=new Map(nodes.map(n=>[n.id,n]));const memo=new Map<string,number>();
  const depth=(id:string,seen=new Set<string>()):number=>{if(memo.has(id))return memo.get(id)!;if(seen.has(id))return 0;seen.add(id);const node=byId.get(id);if(!node||!node.parentIds.length){memo.set(id,0);return 0;}const d=1+Math.max(0,...node.parentIds.map(parent=>depth(parent,new Set(seen))));memo.set(id,d);return d;};
  const groups=new Map<number,VisualNode[]>();for(const node of nodes){const d=depth(node.id);const group=groups.get(d)??[];group.push(node);groups.set(d,group);}
  const maxDepth=Math.max(0,...groups.keys());const maxGroup=Math.max(1,...[...groups.values()].map(group=>group.length));
  const width=Math.max(760,260+maxDepth*190);const height=Math.max(500,200+(maxGroup-1)*135);const points=new Map<string,Point>();
  for(const [d,group] of groups){group.sort((a,b)=>a.index-b.index);const usable=Math.max(0,height-180),start=90,gap=group.length===1?0:usable/(group.length-1);group.forEach((node,i)=>points.set(node.id,{x:120+d*190,y:group.length===1?height/2:start+i*gap,depth:d}));}
  return {points,width,height};
}
function latestPositionOnLine(snapshot:Snapshot,lineId:string):string|undefined{
  const order=new Map(snapshot.positions.map((p,i)=>[p.id,i]));
  return snapshot.cartography.memberships.filter(m=>m.lineId===lineId&&order.has(m.positionId)).sort((a,b)=>(order.get(b.positionId)??0)-(order.get(a.positionId)??0))[0]?.positionId;
}
function mapFeatures(snapshot:Snapshot):VisualFeature[]{
  const constraints=new Map(snapshot.cartography.constraints.map(c=>[c.id,c]));const features:VisualFeature[]=[];
  for(const observation of snapshot.cartography.observations)if(observation.positionId)features.push({id:`feature:observation:${observation.id}`,kind:'observation',label:short(observation.detail,46),anchorIds:[observation.positionId],observation});
  for(const constraint of snapshot.cartography.constraints)features.push({id:`feature:constraint:${constraint.id}`,kind:'constraint',label:short(constraint.label,46),anchorIds:[constraint.discoveredAtPositionId],constraint});
  for(const operation of snapshot.cartography.operations){const anchorIds=[...new Set(operation.constraintIds.map(id=>constraints.get(id)?.discoveredAtPositionId).filter((id):id is string=>!!id))];features.push({id:`feature:operation:${operation.id}`,kind:'operation',label:short(operation.name,46),anchorIds,operation});}
  for(const application of snapshot.cartography.applications){const anchor=latestPositionOnLine(snapshot,application.lineId);features.push({id:`feature:application:${application.id}`,kind:'application',label:short(application.adaptation,46),anchorIds:anchor?[anchor]:[],application});}
  for(const encounter of snapshot.cartography.encounters)features.push({id:`feature:encounter:${encounter.id}`,kind:'encounter',label:short(encounter.summary,46),anchorIds:encounter.basisPositionIds,encounter});
  const resolved=unresolvedGestureIds(snapshot);for(const request of snapshot.cartography.gestureRequests)if(request.kind==='weave'&&!resolved.has(request.id)){const proposal=snapshot.cartography.weaveProposals.find(p=>p.requestId===request.id&&p.status==='pending');features.push({id:`feature:weave-request:${request.id}`,kind:'weave-request',label:short(proposal?.summary??request.focus,46),anchorIds:request.basisPositionIds,request,proposal});}
  return features;
}
function featureVisible(feature:VisualFeature,layers:MapLayers):boolean{if(feature.kind==='observation')return layers.evidence;if(feature.kind==='constraint')return layers.structure;if(feature.kind==='operation'||feature.kind==='application')return layers.operations;return layers.encounters;}
function averagePoint(ids:string[],points:Map<string,Point>):Point|undefined{const found=ids.map(id=>points.get(id)).filter((p):p is Point=>!!p);if(!found.length)return;return {x:found.reduce((n,p)=>n+p.x,0)/found.length,y:found.reduce((n,p)=>n+p.y,0)/found.length,depth:0};}
function featurePoint(feature:VisualFeature,points:Map<string,Point>,index:number):Point|undefined{
  const base=averagePoint(feature.anchorIds,points);if(!base)return;
  const offsets:Record<VisualFeature['kind'],[number,number]>={observation:[18,-72],constraint:[18,72],operation:[74,-74],application:[74,74],encounter:[0,-92],'weave-request':[0,92]};
  const [dx,dy]=offsets[feature.kind];const fan=((index%3)-1)*16;return {x:Math.max(38,base.x+dx),y:Math.max(38,base.y+dy+fan),depth:0};
}
export function ShiftChips({shift,empty='Shift was not recorded for this earlier arrival.'}:{shift?:SemanticShift;empty?:string}){if(!shift)return <p className="muted compact">{empty}</p>;return <><div className="shift-row"><span className="micro">What entered</span><div className="chips">{shift.newlySalient.length?shift.newlySalient.map((s,i)=><span className="chip" key={`${s.span}-${i}`}>{s.span}</span>):<span className="muted">No new spans recorded</span>}</div></div>{shift.preservedInvariants.length>0&&<div className="shift-row"><span className="micro">Still holding</span><div className="chips">{shift.preservedInvariants.map((s,i)=><span className="chip invariant" key={`${s}-${i}`}>{s}</span>)}</div></div>}</>}

const featureGlyph:Record<VisualFeature['kind'],string>={observation:'✦',constraint:'△',operation:'⚙',application:'↯',encounter:'◎','weave-request':'≋'};
const featureNoun:Record<VisualFeature['kind'],string>={observation:'Grounded observation',constraint:'Structural pressure',operation:'Operation',application:'Operation in motion',encounter:'Encounter / weave','weave-request':'Weave waiting'};
function nodeNoun(node:VisualNode):string{const dissipated=node.waypoint?.status==='dissipated';return node.type==='waypoint'?(dissipated?'Dissipated direction':'Open direction'):node.type==='branch'?'Saved path':node.type==='draft'?(node.draftStatus==='reserved'?'Saved proposal':'Proposed step'):node.position?.kind==='intention'?'Intention':'Accepted step';}
function nodeGlyph(node:VisualNode):string{const dissipated=node.waypoint?.status==='dissipated';return node.type==='waypoint'?(dissipated?'×':'◇'):node.type==='branch'?'↗':node.type==='draft'?'◌':node.position?.kind==='intention'?'◆':'●';}

export function CartographyMap({snapshot,selected,onSelect}:{snapshot:Snapshot;selected?:string;onSelect:(id:string)=>void}){
  const [view,setView]=useState<'map'|'outline'>(()=>window.matchMedia('(max-width:760px)').matches?'outline':'map');
  const [layers,setLayers]=useState<MapLayers>({evidence:false,structure:false,operations:false,encounters:false});
  const nodes=useMemo(()=>mapNodes(snapshot),[snapshot]);const allFeatures=useMemo(()=>mapFeatures(snapshot),[snapshot]);const features=useMemo(()=>allFeatures.filter(feature=>featureVisible(feature,layers)),[allFeatures,layers]);const {points,width,height}=useMemo(()=>layout(nodes),[nodes]);
  const transitionKinds=useMemo(()=>new Map(snapshot.cartography.transitions.map(t=>[`${t.fromPositionId}->${t.toPositionId}`,t.kind])),[snapshot]);
  const scrollRef=useRef<HTMLDivElement>(null);const [scale,setScale]=useState(1);
  const resolved=useMemo(()=>unresolvedGestureIds(snapshot),[snapshot]);
  function toggleLayer(layer:keyof MapLayers){setLayers(current=>({...current,[layer]:!current[layer]}));}
  function focusCurrent(){const scroller=scrollRef.current;if(!scroller||!selected)return;let point=points.get(selected);if(!point){const index=features.findIndex(f=>f.id===selected);if(index>=0)point=featurePoint(features[index]!,points,index);}if(!point)return;scroller.scrollTo({left:Math.max(0,point.x*scale-scroller.clientWidth/2),top:Math.max(0,point.y*scale-scroller.clientHeight/2),behavior:'smooth'});}
  function fitMap(){const scroller=scrollRef.current;if(!scroller)return;const next=Math.max(.45,Math.min(1,(scroller.clientWidth-24)/width,(scroller.clientHeight-24)/height));setScale(next);requestAnimationFrame(()=>scroller.scrollTo({left:0,top:0,behavior:'smooth'}));}
  return <div className="territory-browser">
    <div className="territory-browser-tools"><div className="view-switch" role="group" aria-label="Territory view"><button type="button" aria-pressed={view==='map'} onClick={()=>setView('map')}>Map</button><button type="button" aria-pressed={view==='outline'} onClick={()=>setView('outline')}>Outline</button></div></div>
    <div className="map-legend" aria-label="Territory legend"><span><b className="legend-glyph accepted" aria-hidden="true">●</b> Accepted step</span><span><b className="legend-glyph proposed" aria-hidden="true">◌</b> Proposed step</span><span><b className="legend-glyph direction" aria-hidden="true">◇</b> Open direction</span><span><b className="legend-glyph branch" aria-hidden="true">↗</b> Saved path</span></div>
    {view==='map'?<><div className="layer-bar" aria-label="Map layers"><span className="micro">LAYERS</span><label><input type="checkbox" aria-label="Evidence" checked={layers.evidence} onChange={()=>toggleLayer('evidence')}/> Evidence <small>{snapshot.cartography.observations.length}</small></label><label><input type="checkbox" aria-label="Structure" checked={layers.structure} onChange={()=>toggleLayer('structure')}/> Structure <small>{snapshot.cartography.constraints.length}</small></label><label><input type="checkbox" aria-label="Operations" checked={layers.operations} onChange={()=>toggleLayer('operations')}/> Operations <small>{snapshot.cartography.operations.length+snapshot.cartography.applications.length}</small></label><label><input type="checkbox" aria-label="Encounters" checked={layers.encounters} onChange={()=>toggleLayer('encounters')}/> Encounters <small>{snapshot.cartography.encounters.length+snapshot.cartography.gestureRequests.filter(g=>g.kind==='weave'&&!resolved.has(g.id)).length}</small></label></div><div className="map-controls" aria-label="Map controls"><button className="quiet" type="button" disabled={!selected} onClick={focusCurrent}>Focus current</button><button className="quiet" type="button" onClick={fitMap}>Fit map</button>{scale<.99&&<button className="quiet" type="button" onClick={()=>setScale(1)}>100%</button>}</div><div ref={scrollRef} className="map-scroll" role="region" aria-label="Exploration map" tabIndex={0}><div className="map-canvas" style={{width:width*scale,height:height*scale}}><div className="map-plane" style={{width,height,transform:`scale(${scale})`}}>
      <svg className="map-edges" viewBox={`0 0 ${width} ${height}`} aria-hidden="true">
        {nodes.flatMap(node=>node.parentIds.map(parent=>{const a=points.get(parent),b=points.get(node.id);if(!a||!b)return null;const mid=(a.x+b.x)/2;const transition=node.type==='arrival'?transitionKinds.get(`${parent}->${node.id}`):undefined;const kind=node.type==='draft'?'proposed':node.type==='waypoint'?'sensed':node.type==='branch'?'branch-held':transition==='rewalked-to'?'rewalk':'';return <path key={`${parent}->${node.id}`} className={`edge ${kind}`} d={`M ${a.x} ${a.y} C ${mid} ${a.y}, ${mid} ${b.y}, ${b.x} ${b.y}`}/>;}))}
        {features.flatMap((feature,index)=>{const fp=featurePoint(feature,points,index);if(!fp)return[];return feature.anchorIds.map(anchor=>{const ap=points.get(anchor);if(!ap)return null;return <path key={`${feature.id}:${anchor}`} className={`feature-tether ${feature.kind}`} d={`M ${ap.x} ${ap.y} Q ${(ap.x+fp.x)/2} ${(ap.y+fp.y)/2-18} ${fp.x} ${fp.y}`}/>;});})}
        {features.filter((f):f is Extract<VisualFeature,{kind:'encounter'}|{kind:'weave-request'}>=>f.kind==='encounter'||f.kind==='weave-request').map(feature=>{const [aId,bId]=feature.anchorIds;const a=points.get(aId??''),b=points.get(bId??'');if(!a||!b)return null;const klass=feature.kind==='encounter'?`encounter-edge ${feature.encounter.kind}`:'encounter-edge pending-weave';const mid=(a.x+b.x)/2;return <path key={`relation-edge:${feature.id}`} className={klass} d={`M ${a.x} ${a.y} C ${mid} ${a.y-72}, ${mid} ${b.y-72}, ${b.x} ${b.y}`}/>;})}
      </svg>
      {nodes.map(node=>{const p=points.get(node.id)!;const root=node.position?.kind==='intention';const dissipated=node.waypoint?.status==='dissipated';return <button key={node.id} type="button" className={`map-node ${node.type} ${dissipated?'dissipated':''} ${root?'root':''} ${selected===node.id?'selected':''}`} style={{left:p.x,top:p.y}} onClick={()=>onSelect(node.id)} aria-label={`${node.type==='waypoint'?(dissipated?'Dissipated direction':'Unvisited direction'):node.type==='branch'?'Held branch':node.type==='draft'?'Proposed arrival':'Visited arrival'}: ${node.label}`}><span className="node-glyph" aria-hidden="true">{nodeGlyph(node)}</span><span className="node-label">{node.label}</span><span className="node-tooltip"><strong>{nodeNoun(node)}</strong>{node.type==='branch'?<span>{node.branch?.direction}</span>:node.type!=='waypoint'?<ShiftChips shift={node.shift}/>:<><span>{node.question}</span>{node.waypoint&&<small>{node.waypoint.provenance}</small>}</>}</span></button>;})}
      {features.map((feature,index)=>{const p=featurePoint(feature,points,index);if(!p)return null;const outcome=feature.kind==='application'?feature.application.outcome:feature.kind==='encounter'?feature.encounter.kind:feature.kind==='weave-request'?(feature.proposal?'review':'waiting'):'';return <button key={feature.id} type="button" className={`map-feature ${feature.kind} ${outcome} ${selected===feature.id?'selected':''}`} style={{left:p.x,top:p.y}} onClick={()=>onSelect(feature.id)} aria-label={`${featureNoun[feature.kind]}: ${feature.label}`}><span aria-hidden="true">{feature.kind==='application'&&feature.application.outcome==='broke-down'?'×':feature.kind==='encounter'&&feature.encounter.kind==='none'?'∅':featureGlyph[feature.kind]}</span><span className="feature-tooltip"><strong>{featureNoun[feature.kind]}</strong>{feature.label}</span></button>;})}
    </div></div></div></>:<CartographyOutline snapshot={snapshot} selected={selected} onSelect={onSelect}/>} 
  </div>;
}

export function CartographyOutline({snapshot,selected,onSelect}:{snapshot:Snapshot;selected?:string;onSelect:(id:string)=>void}){
  const nodes=useMemo(()=>mapNodes(snapshot),[snapshot]);const positionOrder=useMemo(()=>new Map(snapshot.positions.map((p,i)=>[p.id,i])),[snapshot]);
  return <div className="outline-view" role="region" aria-label="Exploration outline">{snapshot.cartography.lines.map(line=>{const memberships=snapshot.cartography.memberships.filter(m=>m.lineId===line.id);const memberIds=new Set(memberships.map(m=>m.positionId));const lineNodes=nodes.filter(node=>node.position?memberIds.has(node.position.id):node.branch?node.branch.lineId===line.id:node.type==='waypoint'?node.parentIds.some(id=>memberIds.has(id)):node.type==='draft'?node.parentIds.some(id=>memberIds.has(id)):false).sort((a,b)=>{const ap=a.position?positionOrder.get(a.position.id)??a.index:a.index;const bp=b.position?positionOrder.get(b.position.id)??b.index:b.index;return ap-bp;});return <section className="outline-line" key={line.id}><header><div><span className="micro">PATH</span><h3>{line.label}</h3></div><span className="outline-line-status">{line.status}</span></header><ol>{lineNodes.map(node=><li key={`${line.id}:${node.id}`}><button type="button" className={`outline-item ${selected===node.id?'selected':''}`} onClick={()=>onSelect(node.id)} aria-label={`${nodeNoun(node)}: ${node.label}`}><span className="outline-glyph" aria-hidden="true">{nodeGlyph(node)}</span><span className="outline-copy"><small>{nodeNoun(node)}</small><strong>{node.label}</strong>{node.type==='branch'&&node.branch&&<span>{node.branch.direction}</span>}{node.type==='waypoint'&&node.question&&<span>{node.question}</span>}</span></button></li>)}</ol></section>;})}</div>;
}

function ObservationDetail({observation}:{observation:Observation}){return <><p className="eyebrow">GROUNDED OBSERVATION</p><h2>{observation.detail}</h2><p className="candidate-note">This entered from outside pure model generation.</p><div className="detail-block"><h3>Provenance</h3><p>{observation.kind} · {observation.source}</p>{observation.observedAt&&<p>Observed {observation.observedAt}</p>}</div></>}
function ConstraintDetail({snapshot,constraint}:{snapshot:Snapshot;constraint:StructuralConstraint}){const evidence=snapshot.cartography.observations.filter(o=>constraint.observationIds.includes(o.id));return <><p className="eyebrow">STRUCTURAL PRESSURE · CANDIDATE</p><h2>{constraint.label}</h2><p>{constraint.description}</p><div className="detail-block"><h3>How it appeared</h3><p>{constraint.provenance}</p></div>{evidence.length>0&&<div className="detail-block"><h3>Grounding</h3>{evidence.map(o=><p key={o.id}>{o.detail}<small>{o.source}</small></p>)}</div>}</>}
function OperationDetail({snapshot,operation}:{snapshot:Snapshot;operation:Operation}){const constraints=snapshot.cartography.constraints.filter(c=>operation.constraintIds.includes(c.id));return <><p className="eyebrow">OPERATION · CANDIDATE</p><h2>{operation.name}</h2><p><strong>Borrowed from:</strong> {operation.originDomain}</p><div className="operation-flow"><span>{operation.inputStructure}</span><b aria-hidden="true">→</b><span>{operation.outputStructure}</span></div><div className="detail-block"><h3>What it preserves</h3><ul>{operation.preserves.map(v=><li key={v}>{v}</li>)}</ul><h3>What it transforms</h3><ul>{operation.transforms.map(v=><li key={v}>{v}</li>)}</ul></div><div className="detail-block"><h3>Executable procedure</h3><ol>{operation.procedure.map((v,i)=><li key={i}>{v}</li>)}</ol></div>{constraints.length>0&&<div className="detail-block"><h3>Structural fit</h3>{constraints.map(c=><p key={c.id}>{c.label}</p>)}</div>}</>}
function ApplicationDetail({snapshot,application}:{snapshot:Snapshot;application:OperationApplication}){const operation=snapshot.cartography.operations.find(o=>o.id===application.operationId);const evidence=snapshot.cartography.observations.filter(o=>application.observationIds.includes(o.id));const revealed=snapshot.cartography.constraints.filter(c=>application.revealedConstraintIds.includes(c.id));return <><p className="eyebrow">{application.outcome==='broke-down'?'PRODUCTIVE BREAKDOWN':'OPERATION IN MOTION'} · {application.outcome}</p><h2>{operation?.name??'Recorded operation application'}</h2><p>{application.adaptation}</p><div className="detail-block"><h3>Protocol</h3><ol>{application.protocol.map((v,i)=><li key={i}>{v}</li>)}</ol></div>{evidence.length>0&&<div className="detail-block"><h3>What happened outside the model</h3>{evidence.map(o=><p key={o.id}>{o.detail}<small>{o.source}</small></p>)}</div>}{revealed.length>0&&<div className="detail-block"><h3>What the friction exposed</h3>{revealed.map(c=><p key={c.id}><strong>{c.label}</strong><br/>{c.description}</p>)}</div>}</>}
function EncounterDetail({snapshot,encounter}:{snapshot:Snapshot;encounter:Encounter}){const lines=snapshot.cartography.lines.filter(l=>encounter.lineIds.includes(l.id));return <><p className="eyebrow">ENCOUNTER / WEAVE · {encounter.kind}</p><h2>{encounter.summary}</h2><div className="chips">{lines.map(l=><span className="chip" key={l.id}>{l.label}</span>)}</div>{encounter.kind==='none'&&<p className="candidate-note">No useful correspondence was found. That is a cartographic result, not a gap the model must repair.</p>}<div className="detail-block"><h3>What remains unresolved</h3><ul>{encounter.uncertainty.map((u,i)=><li key={i}>{u}</li>)}</ul></div><p className="muted">Candidate relation. Resonance proposes; it does not prove.</p></>}
function WeaveRequestDetail({snapshot,request,proposal}:{snapshot:Snapshot;request:WeaveGestureRequest;proposal?:WeaveProposal}){const lines=snapshot.cartography.lines.filter(l=>request.lineIds.includes(l.id));return <><p className="eyebrow">WEAVE · {proposal?'WAITING FOR HUMAN REVIEW':'WAITING FOR CONVERSATION'}</p><h2>{proposal?.summary??request.focus}</h2><div className="chips">{lines.map(l=><span className="chip" key={l.id}>{l.label}</span>)}</div><div className="detail-block"><h3>What the encounter was asked to test</h3><p>{request.focus}</p></div>{proposal&&<><div className="detail-block"><h3>Proposed result · {proposal.kind}</h3><p>{proposal.summary}</p></div><p className="candidate-note">This relation is still proposed. It is not an Encounter until human review keeps it.</p></>}</>}
function TraversalDetail({snapshot,traversal}:{snapshot:Snapshot;traversal:Traversal}){const line=snapshot.cartography.lines.find(l=>l.id===traversal.lineId);const rewalked=traversal.rewalkOfPositionId?snapshot.positions.find(p=>p.id===traversal.rewalkOfPositionId):undefined;const c=traversal.context;return <div className="detail-block traversal-detail"><h3>{traversal.mode==='rewalk'?'Re-walk conditions':'Traversal'}</h3><p>{line?.label??'Recorded line'} · {traversal.mode}</p>{rewalked&&<p><strong>Revisited:</strong> {rewalked.meaning}</p>}{c?<><p className="muted">Declared context · {c.provenance}. These labels are not a replay or reproducibility guarantee.</p><div className="chips">{c.host&&<span className="chip">host: {c.host}</span>}{c.model&&<span className="chip">model: {c.model}</span>}{c.modelRevision&&<span className="chip">model rev: {c.modelRevision}</span>}{c.skillRevision&&<span className="chip">skill: {c.skillRevision}</span>}{c.sessionLabel&&<span className="chip">session: {c.sessionLabel}</span>}</div>{c.notes&&<p>{c.notes}</p>}</>:<p className="muted">No host/model context was declared for this traversal.</p>}</div>}

export function MapDetail({snapshot,selected}:{snapshot:Snapshot;selected?:string}){
  const node=mapNodes(snapshot).find(n=>n.id===selected);if(node){
    if(node.type==='branch')return <section className="detail-card branch-detail"><p className="eyebrow">HELD BRANCH · UNWALKED</p><h2>{node.branch?.label}</h2><p>{node.branch?.direction}</p><p className="candidate-note">This line exists so the alternative remains available. No Arrival has been visited on it yet.</p></section>;
    if(node.type==='waypoint'){const dissipated=node.waypoint?.status==='dissipated';return <section className={`detail-card waypoint-detail ${dissipated?'dissipated':''}`}><p className="eyebrow">{dissipated?'DISSIPATED DIRECTION':'UNVISITED DIRECTION'}</p><h2>{node.question}</h2><p>{dissipated?'This route was deliberately allowed to fall out of the live frontier. It remains visible because paths not taken are part of the map.':'This route is visible from the current territory, but it has not been walked. It is not an accepted finding.'}</p>{node.waypoint?<div className="detail-block"><h3>How this direction appeared</h3><p>{node.waypoint.provenance}</p>{node.waypoint.resolutionNote&&<p><strong>Why it dissipated:</strong> {node.waypoint.resolutionNote}</p>}</div>:<p className="legacy-note">This direction is projected from an older arrival's saved next question; its original route provenance was not recorded.</p>}</section>}
    const source=node.position??node.proposal!;const shift=node.shift;const missing=node.position?.kind==='intention'?'The root intention is the starting place; it has no prior semantic shift.':'This arrival predates semantic-shift recording. Shadow Walker will not invent a historical shift after the fact.';const nearbyObs=snapshot.cartography.observations.filter(o=>o.positionId===node.position?.id);const nearbyConstraints=snapshot.cartography.constraints.filter(c=>c.discoveredAtPositionId===node.position?.id);const memberships=node.position?snapshot.cartography.memberships.filter(m=>m.positionId===node.position!.id):[];const lines=memberships.map(m=>snapshot.cartography.lines.find(l=>l.id===m.lineId)).filter((l):l is NonNullable<typeof l>=>!!l);const traversal=node.position?.originMoveId?snapshot.cartography.traversals.find(t=>t.moveId===node.position!.originMoveId):undefined;
    return <section className="detail-card"><p className="eyebrow">{node.type==='draft'?(node.draftStatus==='reserved'?'SAVED FOR LATER':'PROPOSED STEP'):'VISITED ARRIVAL'}</p><h2>{source.meaning}</h2>{lines.length>0&&<div className="chips line-membership">{lines.map(l=><span className="chip" key={l.id}>{l.label}</span>)}</div>}{shift?<><p className="shift-summary">{shift.summary}</p><ShiftChips shift={shift}/>{shift.receded.length>0&&<div className="detail-block"><h3>What receded</h3><p>{shift.receded.map(s=>s.span).join(' · ')}</p></div>}<div className="detail-block"><h3>Surprise</h3><p><strong>{shift.surprise.level}</strong> · {shift.surprise.notes}</p></div>{shift.unexpectedConnections.length>0&&<div className="detail-block"><h3>Unexpected connections</h3><ul>{shift.unexpectedConnections.map((v,i)=><li key={i}>{v}</li>)}</ul></div>}</>:<p className="legacy-note">{missing}</p>}{traversal&&<TraversalDetail snapshot={snapshot} traversal={traversal}/>} {source.anchors.length>0&&<div className="detail-block"><h3>Grounding</h3>{source.anchors.map(a=><p key={a.id}>{a.detail}{a.source&&<small>{a.source}</small>}</p>)}</div>}{(nearbyObs.length>0||nearbyConstraints.length>0)&&<div className="detail-block"><h3>Ecology around this arrival</h3>{nearbyConstraints.map(c=><p key={c.id}><strong>{c.label}</strong> · structural pressure</p>)}{nearbyObs.map(o=><p key={o.id}>{o.detail}<small>{o.source}</small></p>)}</div>}{source.uncertainty.length>0&&<div className="detail-block"><h3>What we're unsure about</h3><ul>{source.uncertainty.map((u,i)=><li key={i}>{u}</li>)}</ul></div>}<div className="next"><span className="micro">Where this leads</span><p>{source.nextQuestion}</p></div><details><summary>Patterns &amp; developer details</summary>{source.structuralViews.map((v,i)=><div className="structure" key={i}><h3>{v.label}</h3><p>{v.relationships.join('; ')}</p><p><strong>Applies:</strong> {v.applicability}</p><p><strong>Mismatches:</strong> {v.mismatches.join('; ')||'None recorded'}</p></div>)}{node.position&&<><code>{node.position.id}</code><p>Parents: {node.position.parentIds.join(', ')||'Root intention'}</p></>}</details></section>;
  }
  const feature=mapFeatures(snapshot).find(f=>f.id===selected);if(!feature)return <section className="detail-card empty-detail"><p className="eyebrow">MAP READING</p><h2>Select a place or relation</h2><p>Choose an Arrival, held branch, open direction, structural pressure, operation, application, or weave. The map keeps schema details behind the territory.</p></section>;
  return <section className={`detail-card feature-detail ${feature.kind}`}>{feature.kind==='observation'?<ObservationDetail observation={feature.observation}/>:feature.kind==='constraint'?<ConstraintDetail snapshot={snapshot} constraint={feature.constraint}/>:feature.kind==='operation'?<OperationDetail snapshot={snapshot} operation={feature.operation}/>:feature.kind==='application'?<ApplicationDetail snapshot={snapshot} application={feature.application}/>:feature.kind==='encounter'?<EncounterDetail snapshot={snapshot} encounter={feature.encounter}/>:<WeaveRequestDetail snapshot={snapshot} request={feature.request} proposal={feature.proposal}/>}</section>;
}
