import { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { App } from '@modelcontextprotocol/ext-apps';
import type { CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import type { MoveOutput, Proposal, ReviewInput, ReviewTicket, SemanticShift, Snapshot } from '../../../packages/domain/src/index.ts';
import { CartographyMap, MapDetail, ShiftChips } from './cartography.tsx';
import './style.css';

const bridge=new App({name:'shadow-walker-review',version:'0.3.0'},{});
const clone=<T,>(value:T):T=>structuredClone(value);
const lines=(value:string)=>value.split('\n').map(v=>v.trim()).filter(Boolean);
const spans=(value:string)=>value.split(',').map(v=>v.trim()).filter(Boolean).slice(0,16).map(span=>({span,salience:'medium' as const}));

function defaultShift(p:Proposal):SemanticShift{return {baselineArrivalIds:[p.parentIds[0]!],summary:'Describe how the semantic territory changed at this step.',newlySalient:[],receded:[],preservedInvariants:[],unexpectedConnections:[],newAffordances:[],surprise:{level:'medium',notes:'Describe what was surprising or unsurprising about the movement.'}};}

function Workbench(){
  const [snapshot,setSnapshot]=useState<Snapshot>();const [ticket,setTicket]=useState<ReviewTicket>();const [focused,setFocused]=useState<string>();
  const [selected,setSelected]=useState<string>();const [editing,setEditing]=useState(false);const [editOutput,setEditOutput]=useState<MoveOutput>();
  const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const retry=useRef<{signature:string;requestId:string}|undefined>(undefined);
  const draft=snapshot?.drafts.find(d=>d.id===focused);const original=draft?JSON.stringify(draft.output):'';const dirty=!!editOutput&&JSON.stringify(editOutput)!==original;
  const reviewable=draft?.status==='pending'||draft?.status==='reserved';const permitted=!!ticket&&ticket.draftId===draft?.id&&ticket.version===draft?.version;
  useEffect(()=>{if(window.parent!==window&&window.location.pathname==='/app/widget')window.parent.postMessage({type:'shadow-walker/ui-state',dirty,busy},'*');},[dirty,busy]);
  function receive(result:CallToolResult){
    if(result.isError)throw new Error(result.content.filter(c=>c.type==='text').map(c=>c.text).join('\n'));
    const data=result.structuredContent as {snapshot?:Snapshot;focusedDraftId?:string}|undefined;if(!data?.snapshot)return;
    setSnapshot(data.snapshot);setFocused(data.focusedDraftId);const d=data.snapshot.drafts.find(d=>d.id===data.focusedDraftId);
    setEditOutput(d?clone(d.output):undefined);setTicket(result._meta?.['shadowWalker/review'] as ReviewTicket|undefined);setEditing(false);setError('');setNotice('');
    if(d&&(d.status==='pending'||d.status==='reserved'))setSelected(`proposal:${d.id}:${d.output.positions[0]?.localId}`);else setSelected(data.snapshot.positions.at(-1)?.id);
  }
  useEffect(()=>{bridge.ontoolresult=result=>{try{receive(result);}catch(e){setError(String(e));}};void bridge.connect().catch(()=>setError('Open this view in a trusted MCP Apps host. Review actions require the host bridge.'));return()=>{void bridge.close();};},[]);
  async function reopen(draftId?:string){if(!snapshot)return;setBusy(true);setNotice('');try{receive(await bridge.callServerTool({name:'open_exploration',arguments:{explorationId:snapshot.exploration.id,...(draftId?{draftId}:{})}}));retry.current=undefined;}catch(e){setError(String(e));}finally{setBusy(false);}}
  async function review(action:ReviewInput['action']){if(!ticket||!draft||!permitted)return;setBusy(true);setError('');setNotice('');try{
    const args={draftId:draft.id,expectedVersion:draft.version,token:ticket.token,action,...(action==='revise'?{output:editOutput}:{})};const signature=JSON.stringify(args);
    if(retry.current?.signature!==signature)retry.current={signature,requestId:crypto.randomUUID()};receive(await bridge.callServerTool({name:'review_draft',arguments:{...args,requestId:retry.current.requestId}}));retry.current=undefined;
    setNotice(action==='land'?'Kept. This arrival remains a hypothesis, and the walk is paused.':action==='revise'?'Revision saved. Read the changed step again before keeping it.':action==='reserve'?'Saved for later without adding it to visited territory.':'Discarded from the live map; its history remains recorded.');
  }catch(e){setError(String(e));}finally{setBusy(false);}}
  function updateProposal(index:number,fn:(p:Proposal)=>Proposal){if(!editOutput)return;const output=clone(editOutput);output.positions[index]=fn(output.positions[index]!);setEditOutput(output);}
  return <main className="workbench"><header><div><p className="eyebrow">LATENT-SPACE CARTOGRAPHY</p><h1>Shadow Walker</h1></div><span className="badge">The map is made by walking</span></header>
    <p className="principle">Follow what changes the next question. Preserve the paths not taken.</p>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}
    {!snapshot?<section><h2>Waiting for an exploration</h2><p>Begin in conversation. Shadow Walker will map only territory the walk actually reaches.</p></section>:<>
      <section className="intention"><p className="eyebrow">ORIGINAL INTENTION · REVISION {snapshot.exploration.revision}</p><h2>{snapshot.exploration.title}</h2><p>{snapshot.exploration.intention}</p><div className="line-strip">{snapshot.cartography.lines.map(line=><span className="line-pill" key={line.id}>{line.label} · {line.status}</span>)}</div>
        <details><summary>Working frame</summary><p>{snapshot.exploration.frame.label}</p><ul>{snapshot.exploration.frame.constraints.map((c,i)=><li key={i}>{c}</li>)}</ul></details></section>
      {snapshot.activeMove&&!snapshot.drafts.some(d=>d.moveId===snapshot.activeMove?.moveId)&&<p role="status" className="notice">A walk is prepared on {snapshot.activeMove.line?.label??'a legacy line'} but has no proposed arrival yet. Resume it in the conversation.</p>}
      <div className="map-layout"><section className="map-card"><div className="map-heading"><div><p className="eyebrow">TERRITORY</p><h2>{snapshot.positions.length} visited arrival{snapshot.positions.length===1?'':'s'}</h2></div><p>Hover or focus a node to see what entered there. Hollow nodes are sensed, not visited.</p></div><CartographyMap snapshot={snapshot} selected={selected} onSelect={setSelected}/></section><MapDetail snapshot={snapshot} selected={selected}/></div>
      {draft&&<section className="review-card"><p className="eyebrow">{draft.status==='reserved'?'SAVED FOR LATER':'PROPOSED STEP'} · REVISION {draft.version}</p><h2>Do you want this movement to become part of the map?</h2><p>Keeping it records that this arrival belongs to the exploration. It does not establish that the claim is true.</p>
        {draft.output.positions.map((p,i)=><article className="proposal-card" key={p.localId}><h3>{p.meaning}</h3>{p.semanticShift&&<><p className="shift-summary">{p.semanticShift.summary}</p><ShiftChips shift={p.semanticShift}/></>}<div className="next"><span className="micro">Question opened</span><p>{p.nextQuestion}</p></div><p className="muted">{p.uncertainty.join(' ')}</p>
          {editing&&editOutput&&<div className="human-editor"><label>Main idea<textarea value={editOutput.positions[i]!.meaning} onChange={e=>updateProposal(i,p=>({...p,meaning:e.target.value}))}/></label><label>Question this opens<textarea value={editOutput.positions[i]!.nextQuestion} onChange={e=>updateProposal(i,p=>({...p,nextQuestion:e.target.value}))}/></label><label>What we're unsure about <span>(one per line)</span><textarea value={editOutput.positions[i]!.uncertainty.join('\n')} onChange={e=>updateProposal(i,p=>({...p,uncertainty:lines(e.target.value)}))}/></label>
            <fieldset><legend>Semantic movement</legend><label>What changed<textarea value={(editOutput.positions[i]!.semanticShift??defaultShift(p)).summary} onChange={e=>updateProposal(i,p=>({...p,semanticShift:{...(p.semanticShift??defaultShift(p)),summary:e.target.value}}))}/></label><label>New language / spans <span>(comma separated)</span><input value={(editOutput.positions[i]!.semanticShift??defaultShift(p)).newlySalient.map(s=>s.span).join(', ')} onChange={e=>updateProposal(i,p=>({...p,semanticShift:{...(p.semanticShift??defaultShift(p)),newlySalient:spans(e.target.value)}}))}/></label><label>What receded <span>(comma separated)</span><input value={(editOutput.positions[i]!.semanticShift??defaultShift(p)).receded.map(s=>s.span).join(', ')} onChange={e=>updateProposal(i,p=>({...p,semanticShift:{...(p.semanticShift??defaultShift(p)),receded:spans(e.target.value)}}))}/></label><label>What still held <span>(one per line)</span><textarea value={(editOutput.positions[i]!.semanticShift??defaultShift(p)).preservedInvariants.join('\n')} onChange={e=>updateProposal(i,p=>({...p,semanticShift:{...(p.semanticShift??defaultShift(p)),preservedInvariants:lines(e.target.value)}}))}/></label><label>Surprise<select value={(editOutput.positions[i]!.semanticShift??defaultShift(p)).surprise.level} onChange={e=>updateProposal(i,p=>({...p,semanticShift:{...(p.semanticShift??defaultShift(p)),surprise:{...(p.semanticShift??defaultShift(p)).surprise,level:e.target.value as 'low'|'medium'|'high'}}}))}><option>low</option><option>medium</option><option>high</option></select></label><label>Surprise notes<textarea value={(editOutput.positions[i]!.semanticShift??defaultShift(p)).surprise.notes} onChange={e=>updateProposal(i,p=>({...p,semanticShift:{...(p.semanticShift??defaultShift(p)),surprise:{...(p.semanticShift??defaultShift(p)).surprise,notes:e.target.value}}}))}/></label></fieldset>
            <fieldset><legend>Grounding</legend>{editOutput.positions[i]!.anchors.map((a,ai)=><div className="anchor-edit" key={a.id}><label>Anchor<textarea value={a.detail} onChange={e=>updateProposal(i,p=>{const anchors=clone(p.anchors);anchors[ai]={...anchors[ai]!,detail:e.target.value};return {...p,anchors};})}/></label><label>Source / provenance<input value={a.source??''} onChange={e=>updateProposal(i,p=>{const anchors=clone(p.anchors);anchors[ai]={...anchors[ai]!,source:e.target.value||undefined};return {...p,anchors};})}/></label></div>)}</fieldset>
          </div>}
          <details><summary>Patterns &amp; developer details</summary><pre>{JSON.stringify(p,null,2)}</pre></details></article>)}
        {reviewable&&<><div className="review-actions">{editing?<><button className="primary" disabled={busy||!permitted||!dirty} onClick={()=>void review('revise')}>Save revision</button><button disabled={busy} onClick={()=>{setEditOutput(clone(draft.output));setEditing(false);}}>Cancel changes</button></>:<><button className="primary" disabled={busy||!permitted||dirty} onClick={()=>void review('land')}>Keep this</button><button disabled={busy||!permitted} onClick={()=>setEditing(true)}>Change it</button><button disabled={busy||!permitted||dirty} onClick={()=>void review('reserve')}>Save for later</button><button disabled={busy||!permitted||dirty} onClick={()=>void review('discard')}>Discard</button></>}</div>{!permitted&&<p role="status">Review authorization is unavailable or stale. Refresh this proposed step before acting.</p>}<button className="quiet" disabled={busy||dirty} onClick={()=>void reopen(draft.id)}>Refresh this proposed step</button></>}
      </section>}
      <section className="history-card"><h2>Saved routes &amp; draft history</h2>{snapshot.drafts.length===0?<p>No proposed moves yet.</p>:snapshot.drafts.map(d=><div className="history" key={d.id}><span>{d.status==='landed'?'kept':d.status==='reserved'?'saved for later':d.status} · revision {d.version}</span><button disabled={busy||dirty} onClick={()=>void reopen(d.id)}>Inspect</button></div>)}</section>
      <footer>The territory is unfinished by design. Return to the conversation when you want to move again.</footer>
    </>}
  </main>;
}
createRoot(document.getElementById('root')!).render(<Workbench/>);
